### PR TITLE
Add Angular component

### PR DESCRIPTION
**Pull request by ngyongzhen**
Add Angular component

### CODE REVIEW

**Review by imagekitio — CHANGES_REQUESTED** [review]
We need to mention what all is required by user to make this code work. See ReactJS readme https://github.com/imagekit-samples/quickstart/tree/master/react

**Comment by dev-codesymphony** [comment]
> We need to mention what all is required by user to make this code work. See ReactJS readme https://github.com/imagekit-samples/quickstart/tree/master/react

It's here.
https://github.com/imagekit-samples/quickstart/blob/804366883d5806f288df9dc63ae182d09e835832/angular/README.md

**Comment by ngyongzhen** [comment]
> Please install latest angular sdk from npm and update the package lock file. Please do test once, the sample should be working before PR review.

This is done.

**Comment by imagekitio** [comment]
> > We need to mention what all is required by user to make this code work. See ReactJS readme https://github.com/imagekit-samples/quickstart/tree/master/react
> 
> It's here. https://github.com/imagekit-samples/quickstart/blob/804366883d5806f288df9dc63ae182d09e835832/angular/README.md

I saw that. But it lacks those `.env` related things that are required for both frontend and backend to work. We need explicit, clear instructions in readme.

**Comment by ngyongzhen** [comment]
> > > We need to mention what all is required by user to make this code work. See ReactJS readme https://github.com/imagekit-samples/quickstart/tree/master/react
> > 
> > 
> > It's here. https://github.com/imagekit-samples/quickstart/blob/804366883d5806f288df9dc63ae182d09e835832/angular/README.md
> 
> I saw that. But it lacks those `.env` related things that are required for both frontend and backend to work. We need explicit, clear instructions in readme.

Updated to include need for .env file with PRIVATE_KEY value

**Pull request merged**
